export const tableOption = {
  'border': true,
  'index': true,
  'indexLabel': '序号',
  'stripe': true,
  'menuAlign': 'center',
  'align': 'center',
  'searchMenuSpan': 6,
  'column': [
    {
      'type': 'input',
      'label': '自增id',
      'prop': 'id',
      'span': 12
    }, {
      'type': 'input',
      'label': '市场编码',
      'prop': 'code',
      'span': 12
    }, {
      'type': 'input',
      'label': '市场名称',
      'prop': 'codName',
      'span': 12
    }, {
      'type': 'input',
      'label': '市场简码',
      'prop': 'absCode',
      'span': 12
    }, {
      'type': 'input',
      'label': '所属机构编码',
      'prop': 'orgCode',
      'span': 12
    }, {
      'type': 'input',
      'label': '状态',
      'prop': 'status',
      'span': 12
    }, {
      'type': 'input',
      'label': '省市县',
      'prop': 'region',
      'span': 12
    }, {
      'type': 'input',
      'label': '地址',
      'prop': 'address',
      'span': 12
    }, {
      'type': 'input',
      'label': '开业时间',
      'prop': 'opendate',
      'span': 12
    }, {
      'type': 'input',
      'label': '投资总额',
      'prop': 'invest',
      'span': 12
    }, {
      'type': 'input',
      'label': '占地面积',
      'prop': 'acreage',
      'span': 12
    }, {
      'type': 'input',
      'label': '备注',
      'prop': 'remark',
      'span': 12
    }, {
      'type': 'input',
      'label': '创建者',
      'prop': 'createBy',
      'span': 12
    }, {
      'type': 'input',
      'label': '创建时间',
      'prop': 'createTime',
      'span': 12
    }, {
      'type': 'input',
      'label': '更新者',
      'prop': 'updateBy',
      'span': 12
    }, {
      'type': 'input',
      'label': '更新时间',
      'prop': 'updateTime',
      'span': 12
    }]
}
