export const tableOption = {
  'border': true,
  'index': true,
  'indexLabel': '序号',
  'stripe': true,
  'menuAlign': 'center',
  'align': 'center',
  'searchMenuSpan': 6,
  'column': [
    {
      'type': 'input',
      'label': '自增id',
      'prop': 'id',
      'span': 12
    }, {
      'type': 'input',
      'label': '机构编码',
      'prop': 'code',
      'span': 12
    }, {
      'type': 'input',
      'label': '机构名称',
      'prop': 'codName',
      'span': 12
    }, {
      'type': 'input',
      'label': '级别',
      'prop': 'level',
      'span': 12
    }, {
      'type': 'input',
      'label': '省市县 关联region表 region_code',
      'prop': 'region',
      'span': 12
    }, {
      'type': 'input',
      'label': '地址',
      'prop': 'address',
      'span': 12
    }, {
      'type': 'input',
      'label': '联系电话',
      'prop': 'phone',
      'span': 12
    }, {
      'type': 'input',
      'label': '联系人',
      'prop': 'contactor',
      'span': 12
    }, {
      'type': 'input',
      'label': '备注',
      'prop': 'remark',
      'span': 12
    }, {
      'type': 'input',
      'label': '创建者',
      'prop': 'createBy',
      'span': 12
    }, {
      'type': 'input',
      'label': '创建时间',
      'prop': 'createTime',
      'span': 12
    }, {
      'type': 'input',
      'label': '更新者',
      'prop': 'updateBy',
      'span': 12
    }, {
      'type': 'input',
      'label': '更新时间',
      'prop': 'updateTime',
      'span': 12
    }]
}
